version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/home/cdonato/jdownloader2/config:/config:rw"
      - "/mnt/data/downloads:/output:rw"
