version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 2 * * TUE"
      TZ: Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
